require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AdSetsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AdSet. As you add validations to AdSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Name' }
  }

  let(:invalid_attributes) {
    { name: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdSetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ad_sets as @ad_sets" do
      ad_set = AdSet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ad_sets)).to eq([ad_set])
    end
  end

  describe "GET show" do
    it "assigns the requested ad_set as @ad_set" do
      ad_set = AdSet.create! valid_attributes
      get :show, {:id => ad_set.to_param}, valid_session
      expect(assigns(:ad_set)).to eq(ad_set)
    end
  end

  describe "GET new" do
    it "assigns a new ad_set as @ad_set" do
      get :new, {}, valid_session
      expect(assigns(:ad_set)).to be_a_new(AdSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested ad_set as @ad_set" do
      ad_set = AdSet.create! valid_attributes
      get :edit, {:id => ad_set.to_param}, valid_session
      expect(assigns(:ad_set)).to eq(ad_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdSet" do
        expect {
          post :create, {:ad_set => valid_attributes}, valid_session
        }.to change(AdSet, :count).by(1)
      end

      it "assigns a newly created ad_set as @ad_set" do
        post :create, {:ad_set => valid_attributes}, valid_session
        expect(assigns(:ad_set)).to be_a(AdSet)
        expect(assigns(:ad_set)).to be_persisted
      end

      it "redirects to the created ad_set" do
        post :create, {:ad_set => valid_attributes}, valid_session
        expect(response).to redirect_to(AdSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ad_set as @ad_set" do
        post :create, {:ad_set => invalid_attributes}, valid_session
        expect(assigns(:ad_set)).to be_a_new(AdSet)
      end

      it "re-renders the 'new' template" do
        post :create, {:ad_set => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { name: 'New Name' }
      }

      it "updates the requested ad_set" do
        ad_set = AdSet.create! valid_attributes
        put :update, {:id => ad_set.to_param, :ad_set => new_attributes}, valid_session
        ad_set.reload
        expect(ad_set.name).to eq(new_attributes[:name])
      end

      it "assigns the requested ad_set as @ad_set" do
        ad_set = AdSet.create! valid_attributes
        put :update, {:id => ad_set.to_param, :ad_set => valid_attributes}, valid_session
        expect(assigns(:ad_set)).to eq(ad_set)
      end

      it "redirects to the ad_set" do
        ad_set = AdSet.create! valid_attributes
        put :update, {:id => ad_set.to_param, :ad_set => valid_attributes}, valid_session
        expect(response).to redirect_to(ad_set)
      end
    end

    describe "with invalid params" do
      it "assigns the ad_set as @ad_set" do
        ad_set = AdSet.create! valid_attributes
        put :update, {:id => ad_set.to_param, :ad_set => invalid_attributes}, valid_session
        expect(assigns(:ad_set)).to eq(ad_set)
      end

      it "re-renders the 'edit' template" do
        ad_set = AdSet.create! valid_attributes
        put :update, {:id => ad_set.to_param, :ad_set => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ad_set" do
      ad_set = AdSet.create! valid_attributes
      expect {
        delete :destroy, {:id => ad_set.to_param}, valid_session
      }.to change(AdSet, :count).by(-1)
    end

    it "redirects to the ad_sets list" do
      ad_set = AdSet.create! valid_attributes
      delete :destroy, {:id => ad_set.to_param}, valid_session
      expect(response).to redirect_to(ad_sets_url)
    end
  end

end
