require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlatformInitiativeTypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlatformInitiativeType. As you add validations to PlatformInitiativeType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlatformInitiativeTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all platform_initiative_types as @platform_initiative_types" do
      platform_initiative_type = PlatformInitiativeType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:platform_initiative_types)).to eq([platform_initiative_type])
    end
  end

  describe "GET show" do
    it "assigns the requested platform_initiative_type as @platform_initiative_type" do
      platform_initiative_type = PlatformInitiativeType.create! valid_attributes
      get :show, {:id => platform_initiative_type.to_param}, valid_session
      expect(assigns(:platform_initiative_type)).to eq(platform_initiative_type)
    end
  end

  describe "GET new" do
    it "assigns a new platform_initiative_type as @platform_initiative_type" do
      get :new, {}, valid_session
      expect(assigns(:platform_initiative_type)).to be_a_new(PlatformInitiativeType)
    end
  end

  describe "GET edit" do
    it "assigns the requested platform_initiative_type as @platform_initiative_type" do
      platform_initiative_type = PlatformInitiativeType.create! valid_attributes
      get :edit, {:id => platform_initiative_type.to_param}, valid_session
      expect(assigns(:platform_initiative_type)).to eq(platform_initiative_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlatformInitiativeType" do
        expect {
          post :create, {:platform_initiative_type => valid_attributes}, valid_session
        }.to change(PlatformInitiativeType, :count).by(1)
      end

      it "assigns a newly created platform_initiative_type as @platform_initiative_type" do
        post :create, {:platform_initiative_type => valid_attributes}, valid_session
        expect(assigns(:platform_initiative_type)).to be_a(PlatformInitiativeType)
        expect(assigns(:platform_initiative_type)).to be_persisted
      end

      it "redirects to the created platform_initiative_type" do
        post :create, {:platform_initiative_type => valid_attributes}, valid_session
        expect(response).to redirect_to(PlatformInitiativeType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved platform_initiative_type as @platform_initiative_type" do
        post :create, {:platform_initiative_type => invalid_attributes}, valid_session
        expect(assigns(:platform_initiative_type)).to be_a_new(PlatformInitiativeType)
      end

      it "re-renders the 'new' template" do
        post :create, {:platform_initiative_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested platform_initiative_type" do
        platform_initiative_type = PlatformInitiativeType.create! valid_attributes
        put :update, {:id => platform_initiative_type.to_param, :platform_initiative_type => new_attributes}, valid_session
        platform_initiative_type.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested platform_initiative_type as @platform_initiative_type" do
        platform_initiative_type = PlatformInitiativeType.create! valid_attributes
        put :update, {:id => platform_initiative_type.to_param, :platform_initiative_type => valid_attributes}, valid_session
        expect(assigns(:platform_initiative_type)).to eq(platform_initiative_type)
      end

      it "redirects to the platform_initiative_type" do
        platform_initiative_type = PlatformInitiativeType.create! valid_attributes
        put :update, {:id => platform_initiative_type.to_param, :platform_initiative_type => valid_attributes}, valid_session
        expect(response).to redirect_to(platform_initiative_type)
      end
    end

    describe "with invalid params" do
      it "assigns the platform_initiative_type as @platform_initiative_type" do
        platform_initiative_type = PlatformInitiativeType.create! valid_attributes
        put :update, {:id => platform_initiative_type.to_param, :platform_initiative_type => invalid_attributes}, valid_session
        expect(assigns(:platform_initiative_type)).to eq(platform_initiative_type)
      end

      it "re-renders the 'edit' template" do
        platform_initiative_type = PlatformInitiativeType.create! valid_attributes
        put :update, {:id => platform_initiative_type.to_param, :platform_initiative_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested platform_initiative_type" do
      platform_initiative_type = PlatformInitiativeType.create! valid_attributes
      expect {
        delete :destroy, {:id => platform_initiative_type.to_param}, valid_session
      }.to change(PlatformInitiativeType, :count).by(-1)
    end

    it "redirects to the platform_initiative_types list" do
      platform_initiative_type = PlatformInitiativeType.create! valid_attributes
      delete :destroy, {:id => platform_initiative_type.to_param}, valid_session
      expect(response).to redirect_to(platform_initiative_types_url)
    end
  end

end
