require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlatformInitiativesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlatformInitiative. As you add validations to PlatformInitiative, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlatformInitiativesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all platform_initiatives as @platform_initiatives" do
      platform_initiative = PlatformInitiative.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:platform_initiatives)).to eq([platform_initiative])
    end
  end

  describe "GET show" do
    it "assigns the requested platform_initiative as @platform_initiative" do
      platform_initiative = PlatformInitiative.create! valid_attributes
      get :show, {:id => platform_initiative.to_param}, valid_session
      expect(assigns(:platform_initiative)).to eq(platform_initiative)
    end
  end

  describe "GET new" do
    it "assigns a new platform_initiative as @platform_initiative" do
      get :new, {}, valid_session
      expect(assigns(:platform_initiative)).to be_a_new(PlatformInitiative)
    end
  end

  describe "GET edit" do
    it "assigns the requested platform_initiative as @platform_initiative" do
      platform_initiative = PlatformInitiative.create! valid_attributes
      get :edit, {:id => platform_initiative.to_param}, valid_session
      expect(assigns(:platform_initiative)).to eq(platform_initiative)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlatformInitiative" do
        expect {
          post :create, {:platform_initiative => valid_attributes}, valid_session
        }.to change(PlatformInitiative, :count).by(1)
      end

      it "assigns a newly created platform_initiative as @platform_initiative" do
        post :create, {:platform_initiative => valid_attributes}, valid_session
        expect(assigns(:platform_initiative)).to be_a(PlatformInitiative)
        expect(assigns(:platform_initiative)).to be_persisted
      end

      it "redirects to the created platform_initiative" do
        post :create, {:platform_initiative => valid_attributes}, valid_session
        expect(response).to redirect_to(PlatformInitiative.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved platform_initiative as @platform_initiative" do
        post :create, {:platform_initiative => invalid_attributes}, valid_session
        expect(assigns(:platform_initiative)).to be_a_new(PlatformInitiative)
      end

      it "re-renders the 'new' template" do
        post :create, {:platform_initiative => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested platform_initiative" do
        platform_initiative = PlatformInitiative.create! valid_attributes
        put :update, {:id => platform_initiative.to_param, :platform_initiative => new_attributes}, valid_session
        platform_initiative.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested platform_initiative as @platform_initiative" do
        platform_initiative = PlatformInitiative.create! valid_attributes
        put :update, {:id => platform_initiative.to_param, :platform_initiative => valid_attributes}, valid_session
        expect(assigns(:platform_initiative)).to eq(platform_initiative)
      end

      it "redirects to the platform_initiative" do
        platform_initiative = PlatformInitiative.create! valid_attributes
        put :update, {:id => platform_initiative.to_param, :platform_initiative => valid_attributes}, valid_session
        expect(response).to redirect_to(platform_initiative)
      end
    end

    describe "with invalid params" do
      it "assigns the platform_initiative as @platform_initiative" do
        platform_initiative = PlatformInitiative.create! valid_attributes
        put :update, {:id => platform_initiative.to_param, :platform_initiative => invalid_attributes}, valid_session
        expect(assigns(:platform_initiative)).to eq(platform_initiative)
      end

      it "re-renders the 'edit' template" do
        platform_initiative = PlatformInitiative.create! valid_attributes
        put :update, {:id => platform_initiative.to_param, :platform_initiative => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested platform_initiative" do
      platform_initiative = PlatformInitiative.create! valid_attributes
      expect {
        delete :destroy, {:id => platform_initiative.to_param}, valid_session
      }.to change(PlatformInitiative, :count).by(-1)
    end

    it "redirects to the platform_initiatives list" do
      platform_initiative = PlatformInitiative.create! valid_attributes
      delete :destroy, {:id => platform_initiative.to_param}, valid_session
      expect(response).to redirect_to(platform_initiatives_url)
    end
  end

end
